version: '3'
services:
  nginx: 
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes: 
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
  php: 
    build: .
    volumes:
      - ./:/code
  mysql:
    image: mysql:8.2
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: snowtricks
      MYSQL_USER: snowtricks_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 8081:80
volumes:
  data:
